# Generated by Django 6.1.1 on 2026-09-29 18:37

import django.db.models.deletion
import kyc.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('documento', models.FileField(upload_to=kyc.models.caminho_documento)),
                ('documento_tipo', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=10)),
                ('motivo_recusa', models.TextField(blank=True)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verificacoes', to=settings.AUTH_USER_MODEL)),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=40)),
                ('dados', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to=settings.AUTH_USER_MODEL)),
                ('verificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='kyc.verificacao')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='verificacao',
            index=models.Index(fields=['status', 'criado_em'], name='fila_por_status'),
        ),
        migrations.AddConstraint(
            model_name='verificacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pendente', 'aprovada'])), fields=('cliente',), name='uma_verificacao_ativa_por_cliente'),
        ),
        migrations.AddConstraint(
            model_name='verificacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'recusada'), _negated=True), models.Q(('motivo_recusa', ''), _negated=True), _connector='OR'), name='recusa_exige_motivo'),
        ),
    ]
