# Generated by Django 6.1.1 on 2026-09-30 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0003_contas_de_clientes_aprovados'),
        ('kyc', '0002_auditoria_somente_insercao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoauditoria',
            name='transacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='carteira.transacao'),
        ),
        migrations.AlterField(
            model_name='eventoauditoria',
            name='verificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='kyc.verificacao'),
        ),
        migrations.AddConstraint(
            model_name='eventoauditoria',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verificacao__isnull', False), ('transacao__isnull', True)), models.Q(('verificacao__isnull', True), ('transacao__isnull', False)), _connector='OR'), name='evento_tem_um_alvo'),
        ),
    ]
