# Generated by Django 6.1.1 on 2026-09-30 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('sistema', 'Sistema')], default='cliente', max_length=8)),
                ('nome', models.CharField(blank=True, max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('dono', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('deposito', 'Depósito'), ('saque', 'Saque')], max_length=8)),
                ('valor_centavos', models.BigIntegerField()),
                ('chave_idempotencia', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='carteira.conta')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_centavos', models.BigIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='carteira.conta')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='carteira.transacao')),
            ],
        ),
        migrations.AddConstraint(
            model_name='conta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'cliente'), ('dono__isnull', False)), models.Q(('tipo', 'sistema'), ('dono__isnull', True), models.Q(('nome', ''), _negated=True)), _connector='OR'), name='conta_cliente_tem_dono_sistema_tem_nome'),
        ),
        migrations.AddConstraint(
            model_name='conta',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'sistema')), fields=('nome',), name='nome_unico_conta_sistema'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.UniqueConstraint(fields=('conta', 'chave_idempotencia'), name='idempotencia_por_conta'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.CheckConstraint(condition=models.Q(('valor_centavos__gt', 0), ('valor_centavos__lte', 1000000)), name='valor_da_transacao_no_limite'),
        ),
        migrations.AddConstraint(
            model_name='lancamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_centavos', 0), _negated=True), name='lancamento_nao_nulo'),
        ),
    ]
